package com.sun.entity;
// Generated 2017/6/16 02:32:43 by Hibernate Tools 4.3.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SunBatch generated by hbm2java
 */
@Entity
@Table(name = "sun_batch", catalog = "model_practice")
public class SunBatch implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3269748263700202154L;
	private String id;
	private String cronStr;
	private Date runTime;
	private Date updateTime;
	private String updateUser;

	public SunBatch() {
	}

	public SunBatch(String id, String cronStr, Date runTime, Date updateTime, String updateUser) {
		this.id = id;
		this.cronStr = cronStr;
		this.runTime = runTime;
		this.updateTime = updateTime;
		this.updateUser = updateUser;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 50)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "cron_str", nullable = false, length = 50)
	public String getCronStr() {
		return this.cronStr;
	}

	public void setCronStr(String cronStr) {
		this.cronStr = cronStr;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "run_time", nullable = false, length = 8)
	public Date getRunTime() {
		return this.runTime;
	}

	public void setRunTime(Date runTime) {
		this.runTime = runTime;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "update_time", nullable = false, length = 19)
	public Date getUpdateTime() {
		return this.updateTime;
	}

	public void setUpdateTime(Date updateTime) {
		this.updateTime = updateTime;
	}

	@Column(name = "update_user", nullable = false, length = 50)
	public String getUpdateUser() {
		return this.updateUser;
	}

	public void setUpdateUser(String updateUser) {
		this.updateUser = updateUser;
	}

}
